In [3]:
import numpy as np
frameStart_arr = np.array([0, 10, 20, 30, 40, 50, 60, 80, 100, 120, 150, 180, 210, 240, 270, 300, 360, 420, 480, 540, 600, 720, 840, 960, 1080, 1200, 1500, 1800, 2100, 2337, 2616, 2916])
frameDuration_arr = np.array([10, 10, 10, 10, 10, 10, 20, 20, 20, 30, 30, 30, 30, 30, 30, 60, 60, 60, 60, 60, 120, 120, 120, 120, 120, 300, 300, 300, 237, 279, 300, 300])


In [4]:
End =frameStart_arr + frameDuration_arr

In [5]:
End


array([  10,   20,   30,   40,   50,   60,   80,  100,  120,  150,  180,
        210,  240,  270,  300,  360,  420,  480,  540,  600,  720,  840,
        960, 1080, 1200, 1500, 1800, 2100, 2337, 2616, 2916, 3216])

In [6]:
import temporalimage

In [18]:
import unittest
import numpy as np
import json
import jsonschema
from jsonschema import validate
from temporalimage import Quantity
from temporalimage.t4d import _jsonread_frameTiming

In [19]:
frameStart_arr = np.array([0, 10, 20, 30, 40, 50, 60, 80, 100, 120, 150, 180, 210, 240, 270, 300, 360, 420, 480, 540, 600, 720, 840, 960, 1080, 1200, 1500, 1800, 2100, 2337, 2616, 2916])
frameDuration_arr = np.array([10, 10, 10, 10, 10, 10, 20, 20, 20, 30, 30, 30, 30, 30, 30, 60, 60, 60, 60, 60, 120, 120, 120, 120, 120, 300, 300, 300, 237, 279, 300, 300])


In [24]:
class TestJsonFormat(unittest.TestCase):
    def setUp(self):
	    jsonTestFile = "/opt/anaconda3/envs/toydataset/pet-analysis/tests/test_data/ds001420/sub-01/ses-baseline/pet/sub-01_ses-baseline_pet.json"
        frameStart, frameEnd, jsonDict = _jsonread_frameTiming(jsonTestFile)
        #self.frame_Start = _jsonread_frameTiming(jsonTestFile,frameStart)
        #self.frame_End = _jsonread_frameTiming(jsonTestFile, frameEnd)
        #self.json_Dict = _jsonread_frameTiming(jsonTestFile, jsonDict)
    def test_jsonread_frameTiming(self):
        self.assertEqual(frame_Start, np.allclose(frameStart_arr))
        self.assertEqual(frame_End, np.allclose(frameStart_arr + frameDuration_arr))

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 4)

In [25]:
class TestJsonFormat(unittest.TestCase):
    def setUp(self):
        jsonTestFile = "/opt/anaconda3/envs/toydataset/pet-analysis/tests/test_data/ds001420/sub-01/ses-baseline/pet/sub-01_ses-baseline_pet.json"
        frameStart, frameEnd, jsonDict = _jsonread_frameTiming(jsonTestFile)
    def test_jsonread_frameTiming(self):
        self.assertEqual(frame_Start, np.allclose(frameStart_arr))
        self.assertEqual(frame_End, np.allclose(frameStart_arr + frameDuration_arr))
        
    

In [26]:
jsonTestFile = "/opt/anaconda3/envs/toydataset/pet-analysis/tests/test_data/ds001420/sub-01/ses-baseline/pet/sub-01_ses-baseline_pet.json"
frameStart, frameEnd, jsonDict = _jsonread_frameTiming(jsonTestFile)

In [27]:
frameStart

array([   0,   10,   20,   30,   40,   50,   60,   80,  100,  120,  150,
        180,  210,  240,  270,  300,  360,  420,  480,  540,  600,  720,
        840,  960, 1080, 1200, 1500, 1800, 2100, 2337, 2616, 2916]) <Unit('second')>

In [28]:
frameEnd

array([  10,   20,   30,   40,   50,   60,   80,  100,  120,  150,  180,
        210,  240,  270,  300,  360,  420,  480,  540,  600,  720,  840,
        960, 1080, 1200, 1500, 1800, 2100, 2337, 2616, 2916, 3216]) <Unit('second')>

In [29]:
jsonDict

{'Manufacturer': 'Siemens',
 'ManufacturersModelName': 'High-Resolution Research Tomograph (HRRT, CTI/Siemens)',
 'Units': 'Bq/mL',
 'BodyPart': 'Brain',
 'TracerName': 'DASB',
 'TracerRadionuclide': 'C11',
 'TracerMolecularWeight': 282.39,
 'TracerMolecularWeightUnits': 'g/mol',
 'InjectedRadioactivity': 601.648,
 'InjectedRadioactivityUnits': 'MBq',
 'InjectedMass': 1.55048688915159,
 'InjectedMassUnits': 'ug',
 'MolarActivity': 109.97,
 'MolarActivityUnits': 'GBq/umol',
 'SpecificRadioactivity': 389.4259711746167,
 'SpecificRadioactivityUnits': 'MBq/ug',
 'ModeOfAdministration': 'bolus',
 'TimeZero': '10:33:47',
 'ScanStart': 0,
 'InjectionStart': 0,
 'FrameDuration': [10,
  10,
  10,
  10,
  10,
  10,
  20,
  20,
  20,
  30,
  30,
  30,
  30,
  30,
  30,
  60,
  60,
  60,
  60,
  60,
  120,
  120,
  120,
  120,
  120,
  300,
  300,
  300,
  237,
  279,
  300,
  300],
 'FrameTimesStart': [0,
  10,
  20,
  30,
  40,
  50,
  60,
  80,
  100,
  120,
  150,
  180,
  210,
  240,
  270,
 

In [30]:
import temporalimage
import unittest
import numpy as np
import json
from temporalimage import Quantity
from temporalimage.t4d import _jsonread_frameTiming